# We'll use the '3.x spec since it supports the 'cache_from'
# option:
version: '3.7'

services:
  tests: &lib
    image: docker.pkg.github.com/${GITHUB_REPOSITORY}/main:testing-${GIT_COMMIT_SHORT_SHA}
    build: &lib_build
      target: testing
      context: .
      args: &app_build_args
        CODE_PATH: ${PWD:-/code/on-container}
        DEVELOPER_UID: ${UID:-1000} # Keep in mind, most CI/CD environments will have this variable unset!
        DEVELOPER_USERNAME: ${USER:-you}
      cache_from:
        - docker.pkg.github.com/${GITHUB_REPOSITORY}/main:testing-${GIT_COMMIT_SHORT_SHA}
        - docker.pkg.github.com/${GITHUB_REPOSITORY}/main:testing-${TAG_SAFE_BRANCH}
        - docker.pkg.github.com/${GITHUB_REPOSITORY}/main:testing
    command: rake spec
    volumes:
      - .:${PWD:-/code/on-container}

  release:
    <<: *lib
    image: docker.pkg.github.com/${GITHUB_REPOSITORY}/main:${GIT_COMMIT_SHORT_SHA}
    build:
      <<: *lib_build
      target: builder
    command: rake release
    volumes: []
    environment:
      GEM_HOST_API_KEY: ${GEM_HOST_API_KEY}
