# We'll use the '3.x spec since it supports the 'cache_from'
# option:
version: '3.7'

services:
  tests: &lib
    image: ${DOCKER_NAMESPACE:-icalialabs}/on-container-for-ruby:testing-${GIT_COMMIT_SHORT_SHA}
    build:
      target: testing
      context: .
      args:
        CODE_PATH: ${PWD:-/code/on-container}
        DEVELOPER_UID: ${UID:-1000} # Keep in mind, most CI/CD environments will have this variable unset!
        DEVELOPER_USERNAME: ${USER:-you}
      cache_from:
        - ${DOCKER_NAMESPACE:-icalialabs}/on-container-for-ruby:testing-${GIT_COMMIT_SHORT_SHA}
        - ${DOCKER_NAMESPACE:-icalialabs}/on-container-for-ruby:testing-${TAG_SAFE_BRANCH}
        - ${DOCKER_NAMESPACE:-icalialabs}/on-container-for-ruby:testing
    command: rake spec
    volumes:
      - .:${PWD:-/code/on-container}

  builder:
    <<: *lib
    command: rake build

  release:
    <<: *lib
    command: rake release --trace
    environment:
      GEM_HOST_API_KEY: ${GEM_HOST_API_KEY}
