version: '3.7'

# This docker-compose configuration contents are blank on purpose.
# Development services are located on the `docker-compose.override.yml` file.
# This file should configure services shared across all docker-compose
# environments.