version: "3.7"

volumes:
  gem_bundle:
  command_history:

services:
  on_container:
    image: icalialabs/on-container-for-ruby:development
    build:
      context: .
      target: development
      args:
        APP_PATH: ${PWD}
        DEVELOPER_UID: ${UID:-1000}
        DEVELOPER_USERNAME: ${USER:-you}

    working_dir: ${PWD}

    volumes:
      # Mount the app code into the "/jarvis" folder:
      - .:${PWD}

      # After mounting the app code, this replaces (copies) the image's gem
      # bundle with a volume. We're doing this so we are not forced to re-build
      # the image over and over whenever we install a new gem.
      - gem_bundle:/usr/local/bundle

      # Mount the command history:
      - command_history:/command-history

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true

    # The command we want to execute by default when running the container
    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

    # Specify environment variables available for our app containers. We'll
    # leave a YML anchor in case we need to override or add more variables if
    # needed on each app service:
    environment: &app_environment
      DEBIAN_FRONTEND: dialog
      VSCODE_CONTEXT: "yes"

      # Use VSCode as editor:
      EDITOR: code -w
