name: CI & CD

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

env:
  # Configures docker-compose to use Docker CLI to build the image:
  COMPOSE_DOCKER_CLI_BUILD: 1
  # Configures Docker CLI to use BuildKit to build the image:
  DOCKER_BUILDKIT: 1

jobs:
  test_build:
    name: Build Test Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Add CI/CD scripts to system path
        run: echo "${GITHUB_WORKSPACE}/.github/workflows/bin" >> $GITHUB_PATH

      - name: Normalize env vars
        run: normalize-env-vars >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        id: build_test_image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          target: testing

          platforms: linux/amd64
          
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/on-container-for-ruby:testing-${{ env.GIT_COMMIT_SHORT_SHA }}
            ${{ env.DOCKER_NAMESPACE }}/on-container-for-ruby:testing-${{ env.TAG_SAFE_BRANCH }}
            ${{ env.DOCKER_NAMESPACE }}/on-container-for-ruby:testing-latest
          build-args: |
            CODE_PATH=${{env.PWD}}
            DEVELOPER_UID=${{env.UID}}
            DEVELOPER_USERNAME=${{env.USER}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  testing:
    name: Testing
    runs-on: ubuntu-latest
    needs: [test_build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Add CI/CD scripts to system path
        run: echo "${GITHUB_WORKSPACE}/.github/workflows/bin" >> $GITHUB_PATH

      - name: Normalize env vars
        run: normalize-env-vars >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Load Testing Image
        id: load_test_image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          target: testing
          push: false

          # Make the build result to be available in the Docker client:
          load: true

          platforms: linux/amd64
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/on-container-for-ruby:testing-${{ env.GIT_COMMIT_SHORT_SHA }}
            ${{ env.DOCKER_NAMESPACE }}/on-container-for-ruby:testing-${{ env.TAG_SAFE_BRANCH }}
            ${{ env.DOCKER_NAMESPACE }}/on-container-for-ruby:testing-latest
          build-args: |
            CODE_PATH=${{env.PWD}}
            DEVELOPER_UID=${{env.UID}}
            DEVELOPER_USERNAME=${{env.USER}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests
        run: ci-compose run tests

  release_build:
    name: Build Release
    runs-on: ubuntu-latest
    needs: [test_build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Add CI/CD scripts to system path
        run: echo "${GITHUB_WORKSPACE}/.github/workflows/bin" >> $GITHUB_PATH

      - name: Normalize env vars
        run: normalize-env-vars >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Load Testing Image
        id: load_test_image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          target: testing
          push: false

          # Make the build result to be available in the Docker client:
          load: true

          platforms: linux/amd64
          tags: |
            ${{ env.DOCKER_NAMESPACE }}/on-container-for-ruby:testing-${{ env.GIT_COMMIT_SHORT_SHA }}
            ${{ env.DOCKER_NAMESPACE }}/on-container-for-ruby:testing-${{ env.TAG_SAFE_BRANCH }}
            ${{ env.DOCKER_NAMESPACE }}/on-container-for-ruby:testing-latest
          build-args: |
            CODE_PATH=${{env.PWD}}
            DEVELOPER_UID=${{env.UID}}
            DEVELOPER_USERNAME=${{env.USER}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Gem
        run: ci-compose run builder

      # Persist the built gem for the next job to be able to publish it:
      - name: Persist Built Gem
        uses: actions/upload-artifact@v2
        with:
          name: built-gem
          path: pkg
          retention-days: 1

  publish_gem:
    name: Publish Gem
    runs-on: ubuntu-latest
    needs: [testing, release_build]
    if: github.event_name == 'release'
    env:
      GEM_HOST_API_KEY: ${{ secrets.ICALIALABS_GEM_HOST_API_KEY }}
    steps:
      # Using the GEM_HOST_API_KEY env var to authenticate with Rubygems
      # seems to work only on rubygems version 3.1 onwards... which is included
      # in ruby 2.7.x:
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Restore Built Gem
        uses: actions/download-artifact@v2
        with:
          name: built-gem

      - name: Try to publish
        run: gem push on_container*.gem
        